### ISSUE TITLE
icinga/icingaweb2 on dockerhub needs updated ipl-web module

### ISSUE THREAD

**Issue by yolabingo** [Icinga/docker-icingaweb2#34]
This seemed the most appropriate place to post an issue with an icinga dockerhub image https://hub.docker.com/r/icinga/icingaweb2

error when running icingaweb2:
`Declaration of ipl\Web\Compat\CompatController::setAutorefreshInterval($interval) should be compatible with Icinga\Web\Controller\ActionController::setAutorefreshInterval($interval, $bypassUserPreferences = false)`

This is fixed in the current ipl-web 
https://github.com/Icinga/ipl-web/commit/3244005ae0b5322c3069fcda5e7ba153f11dd8d6

For now, you can workaround by mounting the updated ipl-web in the container

```
git clone https://github.com/lippserd/docker-compose-icinga.git
cd docker-compose-icinga
git clone https://github.com/Icinga/ipl-web.git
```
add to docker-compose.yml:
```
services:
  ...
  icingaweb:
  ...
    volumes:
    - icingaweb:/data
    - ./ipl-web/src:/usr/share/icingaweb2/modules/ipl/vendor/ipl/web/src
```

**Comment by Al2Klimov** [comment]
Hello @yolabingo and thank you for reporting!

Which Docker tag are you using?

Best,
AK

**Comment by trampi** [comment]
Hi @Al2Klimov,

I reproduced this by using the docker-compose.yml linked in this official icinga blog article:
https://icinga.com/blog/2020/08/06/docker-compose-icinga/

[This link leads to the docker-compose.yml from the article](https://github.com/lippserd/docker-compose-icinga/blob/master/docker-compose.yml)

The images used have not always a tag assigned:
```yml
image: icinga/icinga2
image: icinga/icingadb:master
image: icinga/icingaweb2:master
image: mysql
image: redis
```
