### ISSUE TITLE
icinga/icingaweb2:master css build failed

### ISSUE THREAD

**Issue by dwt** [Icinga/docker-icingaweb2#78]
In the current master on docker hub the build for icinga.min.css seems to have failed and instead returns this error:

```less
.appearance is undefined in anonymous-file-0.less
#0 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(143): Less_Tree_Mixin_Call->compile()
#1 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(86): Less_Tree_Ruleset->EvalMixinCalls()
#2 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile()
#3 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Tree/Ruleset.php(91): Less_Tree_Ruleset->compile()
#4 /usr/share/icingaweb2/library/vendor/lessphp/lib/Less/Parser.php(185): Less_Tree_Ruleset->compile()
#5 /usr/share/icingaweb2/library/vendor/lessphp/lessc.inc.php(130): Less_Parser->getCss()
#6 /usr/share/icingaweb2/library/Icinga/Web/LessCompiler.php(230): lessc->compile()
#7 /usr/share/icingaweb2/library/Icinga/Web/StyleSheet.php(207): Icinga\Web\LessCompiler->render()
#8 /usr/share/icingaweb2/library/Icinga/Web/StyleSheet.php(247): Icinga\Web\StyleSheet->render()
#9 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(64): Icinga\Web\StyleSheet::send()
#10 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#11 {main}


.. em;
       width: 1.5em;
     }
   }
   
   .service-grid-link {
     .bg-stateful();
     .rounded-corners();
   
     display: inline-block;
     height: 1.5em;
     vertical-align: middle;
     width: 1.5em;
   }
   }/* Icinga Web 2 | (c) 2021 Icinga GmbH | GPLv2+ */
   
   @enable-color-preference: 999999px;
   @prefer-light-color-scheme: 999999px;
   
..
```

Do you need other input to track this down?
